name: CMake on multiple platforms

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-x86-64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # checkout dependencies
    - name: Checkout deps-gmp
      id: cache-gmp
      uses: actions/cache@v4
      with:
        key: gmp-linux-x86-64
        path: deps/gmp

    - name: Checkout deps-codec
      id: cache-codec
      uses: actions/cache@v4
      with:
        key: codec-linux-x86-64
        path: deps/codec

    - name: Checkout deps-losh
      id: cache-losh
      uses: actions/cache@v4
      with:
        key: losh-linux-x86-64
        path: deps/losh

    - name: Checkout deps-number_converter
      id: cache-number_converter
      uses: actions/cache@v4
      with:
        key: number_converter-linux-x86-64
        path: deps/number_converter

    - name: Checkout deps-ranges
      id: cache-ranges
      uses: actions/cache@v4
      with:
        key: ranges-linux-x86-64
        path: deps/ranges

    - name: Checkout deps-trie
      id: cache-trie
      uses: actions/cache@v4
      with:
        key: trie-linux-x86-64
        path: deps/trie

    - name: Download dependencies
      run: |
        mkdir -p deps

    - name: Download gmp
      if: steps.cache-gmp.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/gmp/latest/linux-x86-64.zip -o gmp.zip
        unzip gmp.zip -d gmp
        rm gmp.zip

    - name: Download codec
      if: steps.cache-codec.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/codec/latest/linux-x86-64.zip -o codec.zip
        unzip codec.zip -d codec
        rm codec.zip

    - name: Download losh
      if: steps.cache-losh.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/losh/latest/linux-x86-64.zip -o losh.zip
        unzip losh.zip -d losh
        rm losh.zip

    - name: Download number_converter
      if: steps.cache-number_converter.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/number_converter/latest/linux-x86-64.zip -o number_converter.zip
        unzip number_converter.zip -d number_converter
        rm number_converter.zip

    - name: Download ranges
      if: steps.cache-ranges.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/ranges/latest/linux-x86-64.zip -o ranges.zip
        unzip ranges.zip -d ranges
        rm ranges.zip

    - name: Download trie
      if: steps.cache-trie.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/trie/latest/linux-x86-64.zip -o trie.zip
        unzip trie.zip -d trie
        rm trie.zip

    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist .
        make install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lit-linux-x86-64-release
        path: dist/*

  build-windows-x86-64:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # checkout dependencies
    - name: Checkout deps-gmp
      id: cache-gmp
      uses: actions/cache@v4
      with:
        key: gmp-windows-x86-64
        path: deps/gmp

    - name: Checkout deps-codec
      id: cache-codec
      uses: actions/cache@v4
      with:
        key: codec-windows-x86-64
        path: deps/codec

    - name: Checkout deps-losh
      id: cache-losh
      uses: actions/cache@v4
      with:
        key: losh-windows-x86-64
        path: deps/losh

    - name: Checkout deps-number_converter
      id: cache-number_converter
      uses: actions/cache@v4
      with:
        key: number_converter-windows-x86-64
        path: deps/number_converter

    - name: Checkout deps-ranges
      id: cache-ranges
      uses: actions/cache@v4
      with:
        key: ranges-windows-x86-64
        path: deps/ranges

    - name: Checkout deps-trie
      id: cache-trie
      uses: actions/cache@v4
      with:
        key: trie-windows-x86-64
        path: deps/trie

    - name: Download dependencies
      run: |
        mkdir -force deps
      
    - name: Download gmp
      if: steps.cache-gmp.outputs.cache-hit != 'true'
      run: |
        cd deps
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/litlang/cpplit-deps/main/gmp/latest/windows-x86-64.zip -OutFile gmp.zip
        Expand-Archive -Path "gmp.zip"
        rm gmp.zip

    - name: Download codec
      if: steps.cache-codec.outputs.cache-hit != 'true'
      run: |
        cd deps
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/litlang/cpplit-deps/main/codec/latest/windows-x86-64.zip -OutFile codec.zip
        Expand-Archive -Path "codec.zip"
        rm codec.zip

    - name: Download losh
      if: steps.cache-losh.outputs.cache-hit != 'true'
      run: |
        cd deps
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/litlang/cpplit-deps/main/losh/latest/windows-x86-64.zip -OutFile losh.zip
        Expand-Archive -Path "losh.zip"
        rm losh.zip

    - name: Download number_converter
      if: steps.cache-number_converter.outputs.cache-hit != 'true'
      run: |
        cd deps
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/litlang/cpplit-deps/main/number_converter/latest/windows-x86-64.zip -OutFile number_converter.zip
        Expand-Archive -Path "number_converter.zip"
        rm number_converter.zip

    - name: Download ranges
      if: steps.cache-ranges.outputs.cache-hit != 'true'
      run: |
        cd deps
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/litlang/cpplit-deps/main/ranges/latest/windows-x86-64.zip -OutFile ranges.zip
        Expand-Archive -Path "ranges.zip"
        rm ranges.zip

    - name: Download trie
      if: steps.cache-trie.outputs.cache-hit != 'true'
      run: |
        cd deps
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/litlang/cpplit-deps/main/trie/latest/windows-x86-64.zip -OutFile trie.zip
        Expand-Archive -Path "trie.zip"
        rm trie.zip

    - name: Build
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_TOOLCHAIN_FILE='cmake/windows-x86-64.cmake' -G "Unix Makefiles"
        make install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lit-windows-x86-64-release
        path: dist/*

  build-macos-arm-64:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # checkout dependencies
    - name: Checkout deps-gmp
      id: cache-gmp
      uses: actions/cache@v4
      with:
        key: gmp-macos-arm-64
        path: deps/gmp

    - name: Checkout deps-codec
      id: cache-codec
      uses: actions/cache@v4
      with:
        key: codec-macos-arm-64
        path: deps/codec

    - name: Checkout deps-losh
      id: cache-losh
      uses: actions/cache@v4
      with:
        key: losh-macos-arm-64
        path: deps/losh

    - name: Checkout deps-number_converter
      id: cache-number_converter
      uses: actions/cache@v4
      with:
        key: number_converter-macos-arm-64
        path: deps/number_converter

    - name: Checkout deps-ranges
      id: cache-ranges
      uses: actions/cache@v4
      with:
        key: ranges-macos-arm-64
        path: deps/ranges

    - name: Checkout deps-trie
      id: cache-trie
      uses: actions/cache@v4
      with:
        key: trie-macos-arm-64
        path: deps/trie

    - name: Download dependencies
      run: |
        mkdir -p deps
          
    - name: Download gmp
      if: steps.cache-gmp.outputs.cache-hit != 'true'
      run: |
        cd deps
        wget https://raw.githubusercontent.com/litlang/cpplit-deps/main/gmp/latest/macos-arm-64.zip -O gmp.zip
        unzip gmp.zip -d gmp
        rm gmp.zip

    - name: Download codec
      if: steps.cache-codec.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/codec/latest/macos-arm-64.zip -o codec.zip
        unzip codec.zip -d codec
        rm codec.zip

    - name: Download losh
      if: steps.cache-losh.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/losh/latest/macos-arm-64.zip -o losh.zip
        unzip losh.zip -d losh
        rm losh.zip

    - name: Download number_converter
      if: steps.cache-number_converter.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/number_converter/latest/macos-arm-64.zip -o number_converter.zip
        unzip number_converter.zip -d number_converter
        rm number_converter.zip

    - name: Download ranges
      if: steps.cache-ranges.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/ranges/latest/macos-arm-64.zip -o ranges.zip
        unzip ranges.zip -d ranges
        rm ranges.zip

    - name: Download trie
      if: steps.cache-trie.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/trie/latest/macos-arm-64.zip -o trie.zip
        unzip trie.zip -d trie
        rm trie.zip

    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist .
        make install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lit-macos-arm-64-release
        path: dist/*

  build-android-arm-64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # checkout dependencies
    - name: Checkout deps-gmp
      id: cache-gmp
      uses: actions/cache@v4
      with:
        key: gmp-android-arm-64
        path: deps/gmp

    - name: Checkout deps-codec
      id: cache-codec
      uses: actions/cache@v4
      with:
        key: codec-android-arm-64
        path: deps/codec

    - name: Checkout deps-losh
      id: cache-losh
      uses: actions/cache@v4
      with:
        key: losh-android-arm-64
        path: deps/losh

    - name: Checkout deps-number_converter
      id: cache-number_converter
      uses: actions/cache@v4
      with:
        key: number_converter-android-arm-64
        path: deps/number_converter

    - name: Checkout deps-ranges
      id: cache-ranges
      uses: actions/cache@v4
      with:
        key: ranges-android-arm-64
        path: deps/ranges

    - name: Checkout deps-trie
      id: cache-trie
      uses: actions/cache@v4
      with:
        key: trie-android-arm-64
        path: deps/trie

    - name: Download dependencies
      run: |
        mkdir -p deps

    - name: Download gmp
      if: steps.cache-gmp.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/gmp/latest/android-arm-64.zip -o gmp.zip
        unzip gmp.zip -d gmp
        rm gmp.zip

    - name: Download codec
      if: steps.cache-codec.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/codec/latest/android-arm-64.zip -o codec.zip
        unzip codec.zip -d codec
        rm codec.zip

    - name: Download losh
      if: steps.cache-losh.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/losh/latest/android-arm-64.zip -o losh.zip
        unzip losh.zip -d losh
        rm losh.zip

    - name: Download number_converter
      if: steps.cache-number_converter.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/number_converter/latest/android-arm-64.zip -o number_converter.zip
        unzip number_converter.zip -d number_converter
        rm number_converter.zip

    - name: Download ranges
      if: steps.cache-ranges.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/ranges/latest/android-arm-64.zip -o ranges.zip
        unzip ranges.zip -d ranges
        rm ranges.zip

    - name: Download trie
      if: steps.cache-trie.outputs.cache-hit != 'true'
      run: |
        cd deps
        curl https://raw.githubusercontent.com/litlang/cpplit-deps/main/trie/latest/android-arm-64.zip -o trie.zip
        unzip trie.zip -d trie
        rm trie.zip

    - name: setup android sdk
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26d
        add-to-path: false

    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_TOOLCHAIN_FILE=cmake/android-arm-64.cmake -DANDROID_NDK_HOME=${{steps.setup-ndk.outputs.ndk-path}} .
        make install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lit-android-arm-64-release
        path: dist/*